version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    networks:
        - rabbitmq_net

volumes:
  rabbitmq:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge
